[workspace]
name = "raja"
version = "0.1.0"
authors = [
    "Simon Akers",
    "Lauren Fleming",
    "James Pruitt <jamescpruitt@gmail.com>",
]
edition = "2021"

members = [
    "model",
    "view",
]

[profile.release]
opt-level = 2 # fast and small wasm