[workspace]
name = "simulator"
version = "0.1.0"
authors = ["James Pruitt <jamescpruitt@gmail.com>"]
edition = "2018"

members = [
    "model",
    "view",
]

[profile.release]
opt-level = 2 # fast and small wasm