name: raja # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: An experimental MIPS32 editor & simulator written in Rust. # 79 char long summary
description: |
  An experimental MIPS32 editor & simulator written in Rust, featuring a GTK4
  front end with a focus on the user experience.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  rust-deps:
    plugin: nil
    build-packages:
      - curl
    override-pull: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

  raja:
    plugin: rust
    source: .
    after:
      - rust-deps

    build-packages:
      - pkg-config
      - libpango1.0-dev
      - libgtk-3-dev
      - libgtk-4-dev
      - libadwaita-1-dev
      - libglib2.0-dev
      - libgtksourceview-5-dev

    stage-packages:
      - libx11-6
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxext6
      - libxi6
      - libxinerama1
      - libxrandr2
      - libadwaita-1-0
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libcairo-gobject2
      - libcairo-script-interpreter2
      - libcairo2
      - libgtk-3-0
      - libgtksourceview-5-0
      - libwayland-cursor++0

slots:
  raja:
    interface: dbus
    bus: session
    name: net.shayes.Raja

apps:
  raja:
    command: bin/raja
    common-id: net.shayes.Raja.desktop

